### ISSUE TITLE
docker-compose up -d 执行报错 求教是版本问题吗

### ISSUE THREAD

**Issue by denkloge** [wsydxiangwang/Mood#11]
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 188, in __init__
  File "docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[30618] Failed to execute script docker-compose

版本如下
![image](https://user-images.githubusercontent.com/22722109/98619352-055f2c80-233e-11eb-9e15-bf284a4748ee.png)

**Comment by denkloge** [comment]
![image](https://user-images.githubusercontent.com/22722109/98620625-96cf9e00-2340-11eb-9f25-e03fa4c40c1b.png)

**Comment by wsydxiangwang** [comment]
我的版本是1.17.1，不过应该跟版本没关系，建议重置服务器后再试试

**Comment by jstJ** [comment]
如何在服务器中跑起来  我的是centos，总是卡在node-sass，导致后续无法编译

**Comment by wsydxiangwang** [comment]
node-sass 是网络问题，npm的锅，找个好网络多试几次、、、现在还在优化，后续应该能解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jstJ"<notifications@github.com&gt;; 
发送时间: 2020年12月30日(星期三) 下午4:44
收件人: "wsydxiangwang/Mood"<Mood@noreply.github.com&gt;; 
抄送: "不如吃茶去v"<1915398623@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [wsydxiangwang/Mood] docker-compose up -d 执行报错 求教是版本问题吗 (#11)





 
如何在服务器中跑起来  我的是centos，总是卡在node-sass，导致后续无法编译

**Comment by jstJ** [comment]
你能直接运行起来实在docker中装了什么环境吗？上传本地的node_moudlues后，server能跑起来，web也跑起来了，但是web报错504，说liuxs环境不支持node-sass

**Comment by wsydxiangwang** [comment]
我的是&nbsp;Ubuntu 18.04&nbsp;，安装docker的时候是否有提示“node-sass”这个东西出错？？ 如有的话，就是网络的问题，暂定未解决..... 后面再找优化方法吧。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jstJ"<notifications@github.com&gt;; 
发送时间: 2020年12月30日(星期三) 下午5:07
收件人: "wsydxiangwang/Mood"<Mood@noreply.github.com&gt;; 
抄送: "不如吃茶去v"<1915398623@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [wsydxiangwang/Mood] docker-compose up -d 执行报错 求教是版本问题吗 (#11)





 
你能直接运行起来实在docker中装了什么环境吗？上传本地的node_moudlues后，server能跑起来，web也跑起来了，但是web报错504，说liuxs环境不支持node-sass

**Comment by wsydxiangwang** [comment]
node-sass 更改为 dart sass，以解决以上 node-sass 报错的问题！

**Comment by zhaozhen1993** [comment]
更改docker文件  下载node-sass 时在后边添加一句  使用淘宝镜像源地址下载
