### ISSUE TITLE
502错误

### ISSUE THREAD

**Issue by soul-cat** [wsydxiangwang/Mood#19]
没有用域名，docker部署能够正常进admin，而后注册或者登录接口全出错。
注册接口刚开始错没注意，后来是停在了不要重复注册那一段代码上，显然数据库连接没有问题。
登录接口出错截图如下。
其中无论是登录接口还是注册接口报错信息都是： RequestResult is not a function

没看到怎么上传图片，代码为：

```
server     | /server/node_modules/mongodb/lib/utils.js:133
server     |       throw err;
server     |       ^
server     |
server     | TypeError: RequestResult is not a function
server     |     at /server/routes/admin/login.js:54:26
server     |     at /server/node_modules/mongoose/lib/model.js:4759:16
server     |     at /server/node_modules/mongoose/lib/query.js:4404:12
server     |     at cb (/server/node_modules/mongoose/lib/query.js:1934:14)
server     |     at /server/node_modules/mongodb/lib/operations/execute_operation.js:75:17
server     |     at executeCallback (/server/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
server     |     at handleCallback (/server/node_modules/mongodb/lib/utils.js:129:55)
server     |     at /server/node_modules/mongodb/lib/operations/to_array.js:36:13
server     |     at handleCallback (/server/node_modules/mongodb/lib/utils.js:129:55)
server     |     at completeClose (/server/node_modules/mongodb/lib/cursor.js:859:16)
server     |     at Cursor.close (/server/node_modules/mongodb/lib/cursor.js:878:12)
server     |     at /server/node_modules/mongodb/lib/operations/to_array.js:35:25
server     |     at /server/node_modules/mongodb/lib/core/cursor.js:750:9
server     |     at handleCallback (/server/node_modules/mongodb/lib/core/cursor.js:32:5)
server     |     at /server/node_modules/mongodb/lib/core/cursor.js:694:38
server     |     at /server/node_modules/mongodb/lib/core/cursor.js:703:39
server     | Emitted 'error' event on Function instance at:
server     |     at /server/node_modules/mongoose/lib/model.js:4761:13
server     |     at /server/node_modules/mongoose/lib/query.js:4404:12
server     |     [... lines matching original stack trace ...]
server     |     at /server/node_modules/mongodb/lib/core/cursor.js:703:39
server     |     at Cursor._endSession (/server/node_modules/mongodb/lib/core/cursor.js:404:7)
```

**Comment by wsydxiangwang** [comment]
你是拉的最新代码吗？？ 我这边本地没有问题呢？？

这个报错是方法名大小写的问题，找不到这个函数，我这边倒没出现这个错误。

并且github有备注还在优化中，暂时不要clone代码，最近忙其他的，就没有时间来搞这个了，完成度大概80%了吧！！！

**Comment by soul-cat** [comment]
看起来是最新代码，辛苦了
