### ISSUE TITLE
服务端启动以后登录注册以后提示这个怎么办

### ISSUE THREAD

**Issue by SlhwSR** [wsydxiangwang/Mood#22]
(node:24844) UnhandledPromiseRejectionWarning: MongoTimeoutError: Server selection timed out after 30000 ms
    at Timeout.setTimeout [as _onTimeout] (D:\Coding\Mood\server\node_modules\mongodb\lib\core\sdam\server_selection.js:308:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:24844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by canyuegongzi** [comment]
解决了吗？
